// SPDX-License-Identifier: LicenseRef-PolyForm-Noncommercial-1.0.0
/// Typed client for the slim-m wire protocol.
///
/// The contract lives in `schema/openapi.yaml`; this package is its Dart side.
/// Two ideas run through it and are worth knowing before use:
///
/// - Identity and order are separate. A message's `id` is a client-generated
///   UUIDv7 that also makes sending idempotent; its `seq` is the server's
///   per-channel order key and the only correct sync cursor.
/// - Writes go over REST and events arrive over the WebSocket. The socket is a
///   fan-out of things that already happened durably, never the write path.
library;

// The extensions are named here too because `show` filters by declaration
// name: an extension's methods need its own name exported to be in scope.
export 'src/client.dart'
    show
        SlimmApi,
        SessionStore,
        AnalyticsDayCount,
        AnalyticsMemorySample,
        AnalyticsStats,
        Bot,
        ChannelStorage,
        DbPoolStats,
        MemberAttachmentUsage,
        NewBot,
        NewWebhook,
        RequestClassCount,
        RouteMetric,
        ServerMetrics,
        SpaceAnalytics,
        SpaceSettings,
        SpaceStorage,
        SweepStatus,
        Webhook,
        SlimmApiAdmin,
        SlimmApiAttachments,
        SlimmApiAuth,
        SlimmApiTotp,
        SlimmApiBotCommands,
        SlimmApiBotUi,
        SlimmApiBots,
        SlimmApiCanvas,
        SlimmApiChannelAdmin,
        SlimmApiDms,
        SlimmApiDock,
        SlimmApiEmoji,
        SlimmApiGifs,
        SlimmApiLinkPreview,
        SlimmApiMemberModeration,
        SlimmApiMessages,
        SlimmApiMetrics,
        SlimmApiModeration,
        SlimmApiModuleCommands,
        SlimmApiModulePermissions,
        SlimmApiNotificationSchedule,
        SlimmApiPresence,
        SlimmApiPush,
        SlimmApiRoles,
        SlimmApiSpace,
        SlimmApiThreads,
        SlimmApiInteractions,
        SlimmApiUsers,
        SlimmApiVoice,
        SlimmApiWatchSession,
        SlimmApiWebhooks,
        JoinPolicy;
export 'src/events.dart'
    show
        CanvasCleared,
        CanvasCursorMoved,
        CanvasMediaSlotChanged,
        CanvasObjectLockChanged,
        CanvasObjectMoved,
        CanvasObjectReordered,
        CanvasObjectPlaced,
        CanvasObjectsRemoved,
        CanvasObjectsRestored,
        CanvasStrokePreview,
        CallRinging,
        CallRingEnded,
        CategoryChanged,
        ChannelCreated,
        ChannelDeleted,
        ChannelUpdated,
        EventConnection,
        EventConnectionRefused,
        ErrorEvent,
        HelloEvent,
        MemberJoined,
        MemberRemoved,
        MemberRestored,
        MemberRoleChanged,
        MemberTimeoutChanged,
        MessageCreated,
        MessageDeleted,
        InteractionAnswered,
        MessageComponentsChanged,
        MessageEphemeral,
        MessageEdited,
        MessagePinned,
        MessageUnpinned,
        NewDeviceSignIn,
        NotificationOverrideChanged,
        OverwriteChanged,
        PollVoted,
        PollOptionTally,
        PongEvent,
        PresenceChanged,
        ProfileChanged,
        BotUiChanged,
        ReactionsChanged,
        ReadStateChanged,
        ReactionTally,
        CodeRunChanged,
        CodeRunsCleared,
        ReportsChanged,
        RoleChanged,
        ServerEvent,
        ThreadUpdated,
        TypingStarted,
        TypingStopped,
        VoiceActivityChanged,
        VoiceParticipantJoined,
        VoiceParticipantLeft,
        VoiceScreenShareChanged,
        WatchTick,
        protocolVersion;
export 'src/exceptions.dart';
export 'src/limits.dart'
    show kMessageMaxChars, kPasswordMinChars, kUserNoteMaxChars;
export 'src/models.dart';
